packages:
  - '.'

overrides:
  js-yaml: ^3.15.2
  '@xmldom/xmldom': ^0.8.15
  baseline-browser-mapping: ^2.11.23
  browserslist: ^4.28.7
  fast-uri: ^3.1.6
  brace-expansion@1: ^1.1.18
  brace-expansion@2: ^2.1.4
  brace-expansion@5: ^5.0.9
  '@babel/core': ^7.29.6
  flatted: ^3.4.2
  picomatch@2: ^2.3.2
  picomatch@4: ^4.0.4
  minimatch@3: ^3.1.5
  minimatch@9: ^9.0.7
  minimatch@10: ^10.2.5
