packages:
  - '.'

overrides:
  js-yaml: ^3.15.2
  '@xmldom/xmldom': ^0.8.15
  baseline-browser-mapping: ^2.11.23
  browserslist: ^4.28.7
  fast-uri: ^3.1.6
  brace-expansion@1: ^1.1.18
  brace-expansion@2: ^2.1.4
  brace-expansion@5: ^5.0.9
